# Generated by Django 6.1 on 2026-08-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
            ],
        ),
    ]
