# Generated by Django 6.1 on 2026-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.IntegerField(max_length=200),
        ),
    ]
